### ISSUE TITLE
oc rsh statements have to be updated in readme

### ISSUE THREAD

**Issue by izapolsk** [ManageIQ/httpd_configmap_generator#23] opened 2018-01-31 13:25 UTC
configs aren't loaded when oc rsh is called. So, httpd_configmap_generator won't be found.
so, such statements have to be updated with using bash for instance.

**Comment by abellotti** [comment] 2018-01-31 14:13
I'm not clear as to what the issue is, can you provide more info about what particular statement is not working for you or your environment, and what you used instead ?  Maybe more details on your setup too, was it plain docker, minishift, openshift, ...  Thanks.

/cc @jvlcek

**Comment by izapolsk** [comment] 2018-01-31 14:39
@abellotti, I added PR. When I run oc exec/rsh httpd_configmap_generator isn't in $PATH. So, there should be either command to load env from config file or bash before.

**Comment by abellotti** [comment] 2018-03-19 17:39
odd, this is working fine for me.

```
# oc rsh $CONFIGMAP_GENERATOR_POD httpd_configmap_generator --help
httpd_configmap_generator 0.2.1 - External Authentication Configuration script

Usage: httpd_configmap_generator auth_type | update | export [--help | options]

supported auth_type: active-directory, ipa, ldap, saml

httpd_configmap_generator options are:
  -V, --version    Version of the httpd_configmap_generator command
  -h, --help       Show this message
```

How did you build/create the httpd_configmap_generator and where are you running it ?  minishift, openshift, etc.

/cc @jvlcek do you have this issue ?

**Comment by jvlcek** [comment] 2018-03-19 20:08
@izapolsk and @abellotti This works fine for me too:


```bash
% oc rsh `oc get pods | grep "httpd-configmap-generator" | cut -f1 -d" "` httpd_configmap_generator --help
httpd_configmap_generator 0.2.1 - External Authentication Configuration script

Usage: httpd_configmap_generator auth_type | update | export [--help | options]

supported auth_type: active-directory, ipa, ldap, saml

httpd_configmap_generator options are:
  -V, --version    Version of the httpd_configmap_generator command
  -h, --help       Show this message
```

**Comment by abellotti** [comment] 2018-03-20 21:06
Thanks @jvlcek for checking 🙇 

@izapolsk is this still an issue for you ? if so how did you create the httpd_configmap_generator pod and are you running on minishift/openshift/etc.  Thanks.

**Comment by izapolsk** [comment] 2018-03-22 12:29
> [root@cmqe-smicro-628-b09 cfme-5920-03211446]# oc get pods
> NAME                                READY     STATUS    RESTARTS   AGE
> cloudforms-0                        1/1       Running   0          10m
> httpd-1-x750b                       1/1       Running   0          10m
> httpd-configmap-generator-1-7l4nv   1/1       Running   0          59s
> memcached-1-vdvtv                   1/1       Running   0          10m
> postgresql-1-2wlsw                  1/1       Running   0          10m
> [root@cmqe-smicro-628-b09 cfme-5920-03211446]# oc rsh httpd-configmap-generator-1-7l4nv httpd_configmap_generator ipa
> rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"httpd_configmap_generator\\\": executable file not found in $PATH\"\n"
> command terminated with exit code 126
> 

> [root@cmqe-smicro-628-b09 cfme-5920-03211446]# oc rsh `oc get pods | grep "httpd-configmap-generator" | cut -f1 -d" "` httpd_configmap_generator --help
> rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"httpd_configmap_generator\\\": executable file not found in $PATH\"\n"
> command terminated with exit code 126
@jvlcek, are you sure you use openshift ? btw, I see this in openshift v3.6. Maybe minishift or openshift v3.7 and/or docker which comes with it behaives in different way

**Comment by jvlcek** [comment] 2018-03-22 14:00
Hello @izapolsk,

Yes I am using Openshift.

```bash
mac% oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://<REMOVED>
openshift v3.6.173.0.21
kubernetes v1.6.1+5115d708d7

mac% oc rsh `oc get pods | grep "httpd-configmap-generator" | cut -f1 -d" "` httpd_configmap_generator --help
httpd_configmap_generator 0.2.1 - External Authentication Configuration
script

Usage: httpd_configmap_generator auth_type | update | export [--help |
options]

supported auth_type: active-directory, ipa, ldap,
saml

httpd_configmap_generator options
are:
  -V, --version    Version of the
                   httpd_configmap_generator
                   command
  -h, --help       Show this message
```

@izapolsk Can you try ssh-ing into the configmap generator pod and report the following:

1. What does `type httpd_configmap_generator` returns? 
2. What's the content of you ~/.bashrc?
3. What's $PATH set to? 

For example:

```bash
mac%  oc rsh ` oc get pods | egrep  "httpd-configmap-generator" | cut -f1 -d" "` bash -i

[root@httpd-configmap-generator-1-jm39z httpd]# type httpd_configmap_generator
httpd_configmap_generator is /opt/rubies/ruby-2.3.1/bin/httpd_configmap_generator

[root@httpd-configmap-generator-1-jm39z httpd]# cat ~/.bashrc
# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

[root@httpd-configmap-generator-1-jm39z httpd]# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rubies/ruby-2.3.1/bin

```

**Comment by simaishi** [comment] 2018-03-22 15:10
This might be due to the difference between non-SCL ruby (upstream) and SCL ruby (downstream).

**Comment by izapolsk** [comment] 2018-03-22 16:34
> [root@cmqe-smicro-628-b09 cmp]# oc rsh httpd-configmap-generator-1-7l4nv 
> sh-4.2# type httpd_configmap_generator
> httpd_configmap_generator is /opt/rh/rh-ruby23/root/usr/bin/httpd_configmap_generator
> sh-4.2# cat ~/.bashrc 
> # .bashrc
> 
> # User specific aliases and functions
> 
> alias rm='rm -i'
> alias cp='cp -i'
> alias mv='mv -i'
> 
> # Source global definitions
> if [ -f /etc/bashrc ]; then
>         . /etc/bashrc
> fi
> sh-4.2# echo $PATH
> /opt/rh/rh-ruby23/root/usr/local/bin:/opt/rh/rh-ruby23/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
>

**Comment by jvlcek** [comment] 2018-03-23 10:21
@izapolsk OK thank you. I think @simaishi might be correct. I will test this with downstream.

**Comment by izapolsk** [comment] 2018-03-23 10:22
@jvlcek, thanks.

**Comment by jvlcek** [comment] 2018-03-29 20:46
@izapolsk and @abellotti 

I was able to reproduce this running downstream bits on OpenShift.

```bash
mac% oc rsh `oc get pods | grep "httpd-configmap-generator" | cut -f1 -d" "` httpd_configmap_generator --help
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"httpd_configmap_generator\\\": executable file not found in $PATH\"\n"
command terminated with exit code 126
mac% 
mac% oc exec `oc get pods | grep "httpd-configmap-generator" | cut -f1 -d" "` -- bash -c 'httpd_configmap_generator --help'
httpd_configmap_generator 0.2.1 - External Authentication Configuration script

Usage: httpd_configmap_generator auth_type | update | export [--help | options]

supported auth_type: active-directory, ipa, ldap, saml

httpd_configmap_generator options are:
  -V, --version    Version of the httpd_configmap_generator command
  -h, --help       Show this message
mac% 
```

I retested it with upstream too.

So I feel this is the correct thing to do.

**Comment by abellotti** [comment] 2018-04-06 13:48
Fixed by https://github.com/ManageIQ/httpd_configmap_generator/pull/24

**Closed by abellotti** 2018-04-06 13:48 UTC
